import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { AppBar } from '@/lib/components/app-bar';
import '../../styles/globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <div className="flex h-dvh flex-col">
                    <header className="sticky top-0 z-50">
                        <AppBar />
                    </header>
                    <main className="min-h-0 w-full flex-1 overflow-y-auto">{children}</main>
                </div>
            </body>
        </html>
    );
}
